version: 2
updates:
  - package-ecosystem: "pip"
    directory: ""
    file: "pyproject.toml"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0  # Only security updates will be opened as PRs
