""" "
Subtensor spec version: 331
"""

System = "System"
Timestamp = "Timestamp"
Grandpa = "Grandpa"
Balances = "Balances"
SubtensorModule = "SubtensorModule"
Utility = "Utility"
Sudo = "Sudo"
Multisig = "Multisig"
Preimage = "Preimage"
Scheduler = "Scheduler"
Proxy = "Proxy"
Registry = "Registry"
Commitments = "Commitments"
AdminUtils = "AdminUtils"
SafeMode = "SafeMode"
Ethereum = "Ethereum"
EVM = "EVM"
BaseFee = "BaseFee"
Drand = "Drand"
Crowdloan = "Crowdloan"
Swap = "Swap"
