FROM python:3.7-slim

 RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        python3-setuptools \
        libffi-dev \
        libssl-dev \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#RUN rm -rf /var/lib/apt/lists/*

# Copy BitTensor source to this image.
RUN mkdir bittensor
COPY . bittensor/
WORKDIR /bittensor

RUN pip3 install -r requirements.txt

# Install Bittensor
RUN pip3 install -e .




  
