[mypy]
ignore_missing_imports = True
ignore_errors = True
follow_imports_for_stubs = True

[mypy-numpy.*]
follow_imports = skip

[mypy-numpy]
follow_imports = skip

[mypy-*.axon.*]
ignore_errors = False

[mypy-*.dendrite.*]
ignore_errors = False

[mypy-bittensor.metagraph.*]
ignore_errors = False

[mypy-*.subtensor.*]
ignore_errors = False

[mypy-*.synapse.*]
ignore_errors = False
