# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bittensor/_proto/text_last_hidden_state/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensors import messages_pb2 as tensors_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bittensor/_proto/text_last_hidden_state/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6bittensor/_proto/text_last_hidden_state/messages.proto\x1a\x16tensors/messages.proto\"\xce\x01\n!ForwardTextLastHiddenStateRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12*\n\x15input_text_serializer\x18\x03 \x01(\x0e\x32\x0b.Serializer\x12\x31\n\x1coutput_embeddings_serializer\x18\x04 \x01(\x0e\x32\x0b.Serializer\x12\x1b\n\ninput_text\x18\x05 \x01(\x0b\x32\x07.Tensor\x12\x0c\n\x04mask\x18\x07 \x01(\x05\"\x94\x01\n\"ForwardTextLastHiddenStateResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12\x1b\n\ninput_text\x18\x03 \x01(\x0b\x32\x07.Tensor\x12\"\n\x11output_embeddings\x18\x04 \x01(\x0b\x32\x07.Tensor\x12\x0c\n\x04mask\x18\x05 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[tensors_dot_messages__pb2.DESCRIPTOR,])




_FORWARDTEXTLASTHIDDENSTATEREQUEST = _descriptor.Descriptor(
  name='ForwardTextLastHiddenStateRequest',
  full_name='ForwardTextLastHiddenStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ForwardTextLastHiddenStateRequest.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='ForwardTextLastHiddenStateRequest.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text_serializer', full_name='ForwardTextLastHiddenStateRequest.input_text_serializer', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_embeddings_serializer', full_name='ForwardTextLastHiddenStateRequest.output_embeddings_serializer', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text', full_name='ForwardTextLastHiddenStateRequest.input_text', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='ForwardTextLastHiddenStateRequest.mask', index=5,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=289,
)


_FORWARDTEXTLASTHIDDENSTATERESPONSE = _descriptor.Descriptor(
  name='ForwardTextLastHiddenStateResponse',
  full_name='ForwardTextLastHiddenStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ForwardTextLastHiddenStateResponse.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='ForwardTextLastHiddenStateResponse.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text', full_name='ForwardTextLastHiddenStateResponse.input_text', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_embeddings', full_name='ForwardTextLastHiddenStateResponse.output_embeddings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='ForwardTextLastHiddenStateResponse.mask', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=440,
)

_FORWARDTEXTLASTHIDDENSTATEREQUEST.fields_by_name['input_text_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_FORWARDTEXTLASTHIDDENSTATEREQUEST.fields_by_name['output_embeddings_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_FORWARDTEXTLASTHIDDENSTATEREQUEST.fields_by_name['input_text'].message_type = tensors_dot_messages__pb2._TENSOR
_FORWARDTEXTLASTHIDDENSTATERESPONSE.fields_by_name['input_text'].message_type = tensors_dot_messages__pb2._TENSOR
_FORWARDTEXTLASTHIDDENSTATERESPONSE.fields_by_name['output_embeddings'].message_type = tensors_dot_messages__pb2._TENSOR
DESCRIPTOR.message_types_by_name['ForwardTextLastHiddenStateRequest'] = _FORWARDTEXTLASTHIDDENSTATEREQUEST
DESCRIPTOR.message_types_by_name['ForwardTextLastHiddenStateResponse'] = _FORWARDTEXTLASTHIDDENSTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForwardTextLastHiddenStateRequest = _reflection.GeneratedProtocolMessageType('ForwardTextLastHiddenStateRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORWARDTEXTLASTHIDDENSTATEREQUEST,
  '__module__' : 'bittensor._proto.text_last_hidden_state.messages_pb2'
  # @@protoc_insertion_point(class_scope:ForwardTextLastHiddenStateRequest)
  })
_sym_db.RegisterMessage(ForwardTextLastHiddenStateRequest)

ForwardTextLastHiddenStateResponse = _reflection.GeneratedProtocolMessageType('ForwardTextLastHiddenStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _FORWARDTEXTLASTHIDDENSTATERESPONSE,
  '__module__' : 'bittensor._proto.text_last_hidden_state.messages_pb2'
  # @@protoc_insertion_point(class_scope:ForwardTextLastHiddenStateResponse)
  })
_sym_db.RegisterMessage(ForwardTextLastHiddenStateResponse)


# @@protoc_insertion_point(module_scope)
