# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bittensor/_proto/text_seq2seq/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensors import messages_pb2 as tensors_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bittensor/_proto/text_seq2seq/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,bittensor/_proto/text_seq2seq/messages.proto\x1a\x16tensors/messages.proto\"X\n\x13TextSeq2SeqResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12 \n\x0fgeneration_text\x18\x05 \x01(\x0b\x32\x07.Tensor\"\xd5\x03\n\x12TextSeq2SeqRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12+\n\x16prompt_text_serializer\x18\x03 \x01(\x0e\x32\x0b.Serializer\x12/\n\x1ageneration_text_serializer\x18\x04 \x01(\x0e\x32\x0b.Serializer\x12\x1c\n\x0bprompt_text\x18\x05 \x01(\x0b\x32\x07.Tensor\x12\x0c\n\x04topk\x18\x06 \x01(\x05\x12\x17\n\x0fnum_to_generate\x18\x07 \x01(\x05\x12\x11\n\tnum_beams\x18\x08 \x01(\x05\x12\x1c\n\x14no_repeat_ngram_size\x18\t \x01(\x05\x12\x16\n\x0e\x65\x61rly_stopping\x18\n \x01(\x08\x12\x1c\n\x14num_return_sequences\x18\x0b \x01(\x05\x12\x11\n\tdo_sample\x18\x0c \x01(\x08\x12\r\n\x05top_p\x18\r \x01(\x02\x12\x13\n\x0btemperature\x18\x0f \x01(\x02\x12\x1a\n\x12repetition_penalty\x18\x10 \x01(\x02\x12\x16\n\x0elength_penalty\x18\x11 \x01(\x02\x12\x10\n\x08max_time\x18\x12 \x01(\x02\x12\x17\n\x0fnum_beam_groups\x18\x13 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[tensors_dot_messages__pb2.DESCRIPTOR,])




_TEXTSEQ2SEQRESPONSE = _descriptor.Descriptor(
  name='TextSeq2SeqResponse',
  full_name='TextSeq2SeqResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='TextSeq2SeqResponse.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='TextSeq2SeqResponse.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generation_text', full_name='TextSeq2SeqResponse.generation_text', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=160,
)


_TEXTSEQ2SEQREQUEST = _descriptor.Descriptor(
  name='TextSeq2SeqRequest',
  full_name='TextSeq2SeqRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='TextSeq2SeqRequest.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='TextSeq2SeqRequest.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prompt_text_serializer', full_name='TextSeq2SeqRequest.prompt_text_serializer', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generation_text_serializer', full_name='TextSeq2SeqRequest.generation_text_serializer', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prompt_text', full_name='TextSeq2SeqRequest.prompt_text', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topk', full_name='TextSeq2SeqRequest.topk', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_to_generate', full_name='TextSeq2SeqRequest.num_to_generate', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_beams', full_name='TextSeq2SeqRequest.num_beams', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='no_repeat_ngram_size', full_name='TextSeq2SeqRequest.no_repeat_ngram_size', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='early_stopping', full_name='TextSeq2SeqRequest.early_stopping', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_return_sequences', full_name='TextSeq2SeqRequest.num_return_sequences', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='do_sample', full_name='TextSeq2SeqRequest.do_sample', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top_p', full_name='TextSeq2SeqRequest.top_p', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='TextSeq2SeqRequest.temperature', index=13,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repetition_penalty', full_name='TextSeq2SeqRequest.repetition_penalty', index=14,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length_penalty', full_name='TextSeq2SeqRequest.length_penalty', index=15,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_time', full_name='TextSeq2SeqRequest.max_time', index=16,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_beam_groups', full_name='TextSeq2SeqRequest.num_beam_groups', index=17,
      number=19, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=632,
)

_TEXTSEQ2SEQRESPONSE.fields_by_name['generation_text'].message_type = tensors_dot_messages__pb2._TENSOR
_TEXTSEQ2SEQREQUEST.fields_by_name['prompt_text_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_TEXTSEQ2SEQREQUEST.fields_by_name['generation_text_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_TEXTSEQ2SEQREQUEST.fields_by_name['prompt_text'].message_type = tensors_dot_messages__pb2._TENSOR
DESCRIPTOR.message_types_by_name['TextSeq2SeqResponse'] = _TEXTSEQ2SEQRESPONSE
DESCRIPTOR.message_types_by_name['TextSeq2SeqRequest'] = _TEXTSEQ2SEQREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextSeq2SeqResponse = _reflection.GeneratedProtocolMessageType('TextSeq2SeqResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEXTSEQ2SEQRESPONSE,
  '__module__' : 'bittensor._proto.text_seq2seq.messages_pb2'
  # @@protoc_insertion_point(class_scope:TextSeq2SeqResponse)
  })
_sym_db.RegisterMessage(TextSeq2SeqResponse)

TextSeq2SeqRequest = _reflection.GeneratedProtocolMessageType('TextSeq2SeqRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTSEQ2SEQREQUEST,
  '__module__' : 'bittensor._proto.text_seq2seq.messages_pb2'
  # @@protoc_insertion_point(class_scope:TextSeq2SeqRequest)
  })
_sym_db.RegisterMessage(TextSeq2SeqRequest)


# @@protoc_insertion_point(module_scope)
