# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testproto/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testproto/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18testproto/messages.proto\"\x19\n\x08\x46Message\x12\r\n\x05thing\x18\x01 \x01(\x05\x32\x30\n\x0bServerThing\x12!\n\x07\x46orward\x12\t.FMessage\x1a\t.FMessage\"\x00\x62\x06proto3'
)




_FMESSAGE = _descriptor.Descriptor(
  name='FMessage',
  full_name='FMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='thing', full_name='FMessage.thing', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['FMessage'] = _FMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FMessage = _reflection.GeneratedProtocolMessageType('FMessage', (_message.Message,), {
  'DESCRIPTOR' : _FMESSAGE,
  '__module__' : 'testproto.messages_pb2'
  # @@protoc_insertion_point(class_scope:FMessage)
  })
_sym_db.RegisterMessage(FMessage)



_SERVERTHING = _descriptor.ServiceDescriptor(
  name='ServerThing',
  full_name='ServerThing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=55,
  serialized_end=103,
  methods=[
  _descriptor.MethodDescriptor(
    name='Forward',
    full_name='ServerThing.Forward',
    index=0,
    containing_service=None,
    input_type=_FMESSAGE,
    output_type=_FMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERTHING)

DESCRIPTOR.services_by_name['ServerThing'] = _SERVERTHING

# @@protoc_insertion_point(module_scope)
