# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opentensor import opentensor_pb2 as opentensor_dot_opentensor__pb2


class OpentensorStub(object):
    """Runtime protocol definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Fwd = channel.unary_unary(
                '/Opentensor/Fwd',
                request_serializer=opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
                response_deserializer=opentensor_dot_opentensor__pb2.TensorMessage.FromString,
                )
        self.Bwd = channel.unary_unary(
                '/Opentensor/Bwd',
                request_serializer=opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
                response_deserializer=opentensor_dot_opentensor__pb2.TensorMessage.FromString,
                )


class OpentensorServicer(object):
    """Runtime protocol definition.
    """

    def Fwd(self, request, context):
        """Forward tensor request. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Bwd(self, request, context):
        """Reverse tensor (gradient) request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpentensorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Fwd': grpc.unary_unary_rpc_method_handler(
                    servicer.Fwd,
                    request_deserializer=opentensor_dot_opentensor__pb2.TensorMessage.FromString,
                    response_serializer=opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
            ),
            'Bwd': grpc.unary_unary_rpc_method_handler(
                    servicer.Bwd,
                    request_deserializer=opentensor_dot_opentensor__pb2.TensorMessage.FromString,
                    response_serializer=opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Opentensor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Opentensor(object):
    """Runtime protocol definition.
    """

    @staticmethod
    def Fwd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Opentensor/Fwd',
            opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
            opentensor_dot_opentensor__pb2.TensorMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Bwd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Opentensor/Bwd',
            opentensor_dot_opentensor__pb2.TensorMessage.SerializeToString,
            opentensor_dot_opentensor__pb2.TensorMessage.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class MetagraphProxyStub(object):
    """DTH + Blockchain interface.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.unary_unary(
                '/MetagraphProxy/Subscribe',
                request_serializer=opentensor_dot_opentensor__pb2.Neuron.SerializeToString,
                response_deserializer=opentensor_dot_opentensor__pb2.ACK.FromString,
                )
        self.Unsubscribe = channel.unary_unary(
                '/MetagraphProxy/Unsubscribe',
                request_serializer=opentensor_dot_opentensor__pb2.Neuron.SerializeToString,
                response_deserializer=opentensor_dot_opentensor__pb2.ACK.FromString,
                )
        self.GetMetagraph = channel.unary_unary(
                '/MetagraphProxy/GetMetagraph',
                request_serializer=opentensor_dot_opentensor__pb2.ACK.SerializeToString,
                response_deserializer=opentensor_dot_opentensor__pb2.Metagraph.FromString,
                )


class MetagraphProxyServicer(object):
    """DTH + Blockchain interface.
    """

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetagraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetagraphProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=opentensor_dot_opentensor__pb2.Neuron.FromString,
                    response_serializer=opentensor_dot_opentensor__pb2.ACK.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=opentensor_dot_opentensor__pb2.Neuron.FromString,
                    response_serializer=opentensor_dot_opentensor__pb2.ACK.SerializeToString,
            ),
            'GetMetagraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetagraph,
                    request_deserializer=opentensor_dot_opentensor__pb2.ACK.FromString,
                    response_serializer=opentensor_dot_opentensor__pb2.Metagraph.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MetagraphProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MetagraphProxy(object):
    """DTH + Blockchain interface.
    """

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MetagraphProxy/Subscribe',
            opentensor_dot_opentensor__pb2.Neuron.SerializeToString,
            opentensor_dot_opentensor__pb2.ACK.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MetagraphProxy/Unsubscribe',
            opentensor_dot_opentensor__pb2.Neuron.SerializeToString,
            opentensor_dot_opentensor__pb2.ACK.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMetagraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MetagraphProxy/GetMetagraph',
            opentensor_dot_opentensor__pb2.ACK.SerializeToString,
            opentensor_dot_opentensor__pb2.Metagraph.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
