# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bittensor/_proto/text_causal_lm_next/messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensors import messages_pb2 as tensors_dot_messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bittensor/_proto/text_causal_lm_next/messages.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3bittensor/_proto/text_causal_lm_next/messages.proto\x1a\x16tensors/messages.proto\"\xc7\x01\n\x1e\x46orwardTextCausalLMNextRequest\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12*\n\x15input_text_serializer\x18\x03 \x01(\x0e\x32\x0b.Serializer\x12-\n\x18output_logits_serializer\x18\x04 \x01(\x0e\x32\x0b.Serializer\x12\x1b\n\ninput_text\x18\x05 \x01(\x0b\x32\x07.Tensor\x12\x0c\n\x04topk\x18\x06 \x01(\x05\"q\n BackwardTextCausalLMNextResponse\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x0e\n\x06hotkey\x18\x02 \x01(\t\x12\x1e\n\routput_logits\x18\x03 \x01(\x0b\x32\x07.Tensor\x12\x0c\n\x04topk\x18\x04 \x01(\x05\x62\x06proto3'
  ,
  dependencies=[tensors_dot_messages__pb2.DESCRIPTOR,])




_FORWARDTEXTCAUSALLMNEXTREQUEST = _descriptor.Descriptor(
  name='ForwardTextCausalLMNextRequest',
  full_name='ForwardTextCausalLMNextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ForwardTextCausalLMNextRequest.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='ForwardTextCausalLMNextRequest.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text_serializer', full_name='ForwardTextCausalLMNextRequest.input_text_serializer', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_logits_serializer', full_name='ForwardTextCausalLMNextRequest.output_logits_serializer', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_text', full_name='ForwardTextCausalLMNextRequest.input_text', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topk', full_name='ForwardTextCausalLMNextRequest.topk', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=279,
)


_BACKWARDTEXTCAUSALLMNEXTRESPONSE = _descriptor.Descriptor(
  name='BackwardTextCausalLMNextResponse',
  full_name='BackwardTextCausalLMNextResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='BackwardTextCausalLMNextResponse.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hotkey', full_name='BackwardTextCausalLMNextResponse.hotkey', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_logits', full_name='BackwardTextCausalLMNextResponse.output_logits', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topk', full_name='BackwardTextCausalLMNextResponse.topk', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=394,
)

_FORWARDTEXTCAUSALLMNEXTREQUEST.fields_by_name['input_text_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_FORWARDTEXTCAUSALLMNEXTREQUEST.fields_by_name['output_logits_serializer'].enum_type = tensors_dot_messages__pb2._SERIALIZER
_FORWARDTEXTCAUSALLMNEXTREQUEST.fields_by_name['input_text'].message_type = tensors_dot_messages__pb2._TENSOR
_BACKWARDTEXTCAUSALLMNEXTRESPONSE.fields_by_name['output_logits'].message_type = tensors_dot_messages__pb2._TENSOR
DESCRIPTOR.message_types_by_name['ForwardTextCausalLMNextRequest'] = _FORWARDTEXTCAUSALLMNEXTREQUEST
DESCRIPTOR.message_types_by_name['BackwardTextCausalLMNextResponse'] = _BACKWARDTEXTCAUSALLMNEXTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ForwardTextCausalLMNextRequest = _reflection.GeneratedProtocolMessageType('ForwardTextCausalLMNextRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORWARDTEXTCAUSALLMNEXTREQUEST,
  '__module__' : 'bittensor._proto.text_causal_lm_next.messages_pb2'
  # @@protoc_insertion_point(class_scope:ForwardTextCausalLMNextRequest)
  })
_sym_db.RegisterMessage(ForwardTextCausalLMNextRequest)

BackwardTextCausalLMNextResponse = _reflection.GeneratedProtocolMessageType('BackwardTextCausalLMNextResponse', (_message.Message,), {
  'DESCRIPTOR' : _BACKWARDTEXTCAUSALLMNEXTRESPONSE,
  '__module__' : 'bittensor._proto.text_causal_lm_next.messages_pb2'
  # @@protoc_insertion_point(class_scope:BackwardTextCausalLMNextResponse)
  })
_sym_db.RegisterMessage(BackwardTextCausalLMNextResponse)


# @@protoc_insertion_point(module_scope)
