name: Auto Assign Cortex to Pull Requests

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto-assign Cortex Team
      uses: kentaro-m/auto-assign-action@v1.2.4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/auto_assign.yml