name: Changelog guard (for release of hotfix)

permissions:
  contents: read

on:
  pull_request:
    branches:
      - 'release/**'
      - 'Release/**'
      - 'hotfix/**'
      - 'Hotfix/**'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v42
        id: changed
      - name: Ensure CHANGELOG.md updated
        if: contains(steps.changed.outputs.all_changed_files, 'CHANGELOG.md') == false
        uses: actions/github-script@v7
        with:
          script: core.setFailed('CHANGELOG.md must be updated.')
